FROM alpine:latest as builder
RUN apk add --no-cache nodejs npm

WORKDIR /app

COPY ./package.json /app
COPY ./package-lock.json  /app
RUN npm install
COPY . .
RUN npm run build
#CMD [ "npm", "run", "build" ]


FROM nginx
COPY --from=builder /app/build /usr/share/nginx/html
