FROM alpine:latest as builder
RUN apk add --no-cache nodejs npm

WORKDIR /app
COPY ./package.json /app
COPY ./package-lock.json /app
RUN npm install
COPY . /app

EXPOSE 3000 80

RUN npm run build

FROM nginx:latest
COPY --from=builder /app/build/ /usr/share/nginx/html
